### ISSUE TITLE
App: Mercado Livre

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-mercado-livre#1]
- [x] Setup do repo (falta o token de parceiro do @thiagoabreudev  );
- [x] Configuração do app seguindo instruções em [next steps](https://github.com/ecomplus/app-mercado-livre#next-steps);
- [x] Rota para envio de produtos da E-Com Plus -> ML:
  1. Checar os atributos respectivos à categoria do ML selecionada;
  2. Parsear as `specifications` e outros campos do corpo do produto na plataforma para o ML como possível;
  3. Em caso de erro registrar uma mensagem explicativa em `/products/:_id/hidden_data.json`;
- [x] Tratar [webhooks](https://github.com/ecomplus/app-mercado-livre#webhook) da E-Com Plus (a partir de procedures configurados) para atualizar no ML as informações dos produtos sincronizados;
- [x] Tratar notificações de novos pedidos no ML registrando na plataforma caso hajam produtos sincronizados inclusos no pedido;
- [x] Adicionar workflow agendado do GitHub Actions para bater uma rota na cloud function que verifique ativamente novos pedidos no ML ou alterações de produtos na plataforma (consumir ativamente as APIs como fallback aos webhooks).
- [ ] Descrição e um ícone legal (@vitorrgg ) pro Market (instruções [aqui](https://github.com/ecomplus/app-mercado-livre#optional-setup-for-market));

**Comment by leomp12** [comment]
Uva :grapes:

**Comment by leomp12** [comment]
@thiagoabreudev talvez isto aqui seja útil pra você atualizar status de pedidos na plataforma se for cancelado ou aprovado no ML: https://gist.github.com/leomp12/3ec7a835dedb5858da57a6ec9f5e81ad

> Talvez seja tarde mas só agora lembrei que escrevi este Gist...

**Comment by leomp12** [comment]
@vitorrgg arruma um ícone pro app no tamanho padrão por favor

**Comment by vitorrgg** [comment]
![ml](https://user-images.githubusercontent.com/35348281/101363695-741da000-3880-11eb-9e72-ae280fde413c.png)
