### ISSUE TITLE
Erro ao vincular conta

### ISSUE THREAD

**Issue by ThaisChaves** [ecomplus/app-mercado-livre#27]
Ao tentar vincular conta, esta dando erro na rota.
https://us-central1-ecom-mercado-livre.cloudfunctions.net/app/mercado-livre/callback?store_id=1117

**Comment by thiagoabreudev** [comment]
Opa @ThaisChaves eu fiz aqui com a loja 1117 e vinculou normalmente. Consegue testar novamente pra podermos ver o que fizemos de diferente?
![image](https://user-images.githubusercontent.com/4981847/103251914-95424f80-4959-11eb-8cb3-31b7b3480238.png)
